# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: post.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'post.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\npost.proto\x12\x04post\"H\n\x04Post\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x0f\n\x07user_id\x18\x02 \x01(\x03\x12\x0f\n\x07\x63ontent\x18\x03 \x01(\t\x12\x12\n\ncreated_at\x18\x04 \x01(\t\"5\n\x11\x43reatePostRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x03\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\".\n\x12\x43reatePostResponse\x12\x18\n\x04post\x18\x01 \x01(\x0b\x32\n.post.Post\")\n\x16ListPostsByUserRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x03\"4\n\x17ListPostsByUserResponse\x12\x19\n\x05posts\x18\x01 \x03(\x0b\x32\n.post.Post2\x9e\x01\n\x0bPostService\x12?\n\nCreatePost\x12\x17.post.CreatePostRequest\x1a\x18.post.CreatePostResponse\x12N\n\x0fListPostsByUser\x12\x1c.post.ListPostsByUserRequest\x1a\x1d.post.ListPostsByUserResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'post_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_POST']._serialized_start=20
  _globals['_POST']._serialized_end=92
  _globals['_CREATEPOSTREQUEST']._serialized_start=94
  _globals['_CREATEPOSTREQUEST']._serialized_end=147
  _globals['_CREATEPOSTRESPONSE']._serialized_start=149
  _globals['_CREATEPOSTRESPONSE']._serialized_end=195
  _globals['_LISTPOSTSBYUSERREQUEST']._serialized_start=197
  _globals['_LISTPOSTSBYUSERREQUEST']._serialized_end=238
  _globals['_LISTPOSTSBYUSERRESPONSE']._serialized_start=240
  _globals['_LISTPOSTSBYUSERRESPONSE']._serialized_end=292
  _globals['_POSTSERVICE']._serialized_start=295
  _globals['_POSTSERVICE']._serialized_end=453
# @@protoc_insertion_point(module_scope)
